version: '2'

volumes:
    logs:
        driver: local

services:
    rectum:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8400 -t public
        environment:
            docker: "true"
        ports:
            - 8400:8400
        volumes:
            - .:/var/www
            - logs:/var/www/logs
